# Generated by Django 4.0.3 on 2022-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinee',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='examinee',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='examinee',
            name='rollno',
            field=models.CharField(default='', max_length=20),
        ),
    ]
