# Generated by Django 4.0.3 on 2022-07-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee', '0002_examinee_email_examinee_name_examinee_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinee',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
