# Generated by Django 4.0.3 on 2022-07-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinee', '0004_alter_examinee_email_alter_examinee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinee',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
