# Generated by Django 4.0.3 on 2022-05-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='examiner',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='questionbank',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('que', models.TextField()),
                ('a', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
                ('d', models.TextField()),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
